# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: pr-automation
on: pull_request

jobs:
  pr-automation:
    uses: hoverinc/action-pr-automation/.github/workflows/pr-automation.yml@ff17e7790c64aea393054aaee43c7f1a65003d1e # v1.2.0
    secrets: inherit
