on: [push]

name: Test

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.x'
          bundler-cache: true

      - name: Cache bundled gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby gems
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Run Rspec
        run: |
          bundle exec rspec
